### ISSUE TITLE
Still maintaining?

### ISSUE THREAD

**Issue by jackofseattle** [tmslnz/gulp-shopify-theme#2]
Hello! Thanks for your work on this package.

I'm curious if you're still maintaining this project and if you have any desire to update it to consumer the newest shopify-node-api package. There were several changes to the api, notably around how you can now update the call limits and bucket sizes for uploads.   With the advent of shopify plus, we now see those call limits being adjusted per merchant (and even per store) so it would be nice to have this package able to take those arguments as well.

If you're not maintaining or have no desire to perform these updates then please respond so I can find a work around.

Thanks!

**Comment by tmslnz** [comment]
Thanks for the heads up. I am still using the package (though not at the moment), so yes it makes sense to give it a little tlc.
Would you like to be added to the repo?

**Comment by tmslnz** [comment]
I’ve just done a comprehensive maintenance pass. Have a look, some new features added like support for custom timeouts and buckets, as well as done and error events
