### ISSUE TITLE
Windows issue

### ISSUE THREAD

**Issue by shelldandy** [tmslnz/gulp-shopify-theme#4]
https://github.com/tmslnz/gulp-shopify-theme/blob/master/index.js#L110

We have found that that line causes problems on Windows machines we have fixed it by replacing it with

`basepath = basepath[0].replace('\\', '/');`

Might be worth taking a look.

Thanks for the awesome plugin

**Comment by tmslnz** [comment]
Thank you for reporting this. I believe this could be solved by using the `path` module which handles platform-specifc formats well.

**Comment by tmslnz** [comment]
Fixed with commit 542d2ac444d0c3cb86b86da291f80be1304a32f3
